---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: centos-6_chef-11
  driver_config:
    box: sendgrid_centos-6.5_chef-11.12.4
    box_url: http://repo.sjc1.sendgrid.net/images/vagrant/sendgrid_centos-6.5_chef-11.12.4.box

suites:
- name: default
  run_list:
  - recipe[collectd]
  - recipe[collectd::attribute_driven]
  attributes:
    collectd:
      graphite_ipaddress: localhost
      plugins:
        write_graphite:
          config: { Prefix: "collectd." }
        syslog:
          config: { LogLevel: "Info" }
        disk: { }
        swap: { }
        memory: { }
        cpu: { }
        interface:
          config: { Interface: "lo", IgnoreSelected: true }
        df:
          config:
            ReportReserved: false
            FSType: [ "proc", "sysfs", "fusectl", "debugfs", "devtmpfs", "devpts", "tmpfs" ]
            IgnoreSelected: true
